import React, { useState } from "react";
import axios from "axios";
import { jsPDF } from "jspdf";
import { serverUrl } from "../App";
import { 
  Calendar, Clock, Download, Trash2, Sparkles, 
  BookOpen, XCircle, Plus, X, Hash, AlertCircle, Edit3
} from "lucide-react";

const daysOfWeek = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"];

const AIScheduler = () => {
  const [subjectInput, setSubjectInput] = useState("");
  const [subjects, setSubjects] = useState([]);
  const [weakInput, setWeakInput] = useState("");
  const [weakSubjects, setWeakSubjects] = useState([]);
  const [offDays, setOffDays] = useState([]);
  const [schedule, setSchedule] = useState(null);
  const [loading, setLoading] = useState(false);
  const [freeTimeSlots, setFreeTimeSlots] = useState(
    daysOfWeek.reduce((acc, d) => ({ ...acc, [d]: [] }), {})
  );

  // -- LIVE EDIT LOGIC FOR GENERATED SCHEDULE --
  const handleEditSchedule = (day, index, field, value) => {
    const updatedSchedule = { ...schedule };
    updatedSchedule[day][index][field] = value;
    setSchedule(updatedSchedule);
  };

  const removeTaskFromSchedule = (day, index) => {
    const updatedSchedule = { ...schedule };
    updatedSchedule[day].splice(index, 1);
    setSchedule(updatedSchedule);
  };

  // -- PDF EXPORT --
  const downloadPDF = () => {
    if (!schedule) return;
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    let y = 20;

    // --- HEADER SECTION ---
    doc.setFillColor(15, 23, 42); // Dark Slate Background (same as UI)
    doc.rect(0, 0, pageWidth, 40, "F");
    
    doc.setTextColor(34, 211, 238); // Cyan Color
    doc.setFont("helvetica", "bold");
    doc.setFontSize(24);
    doc.text("STUDY_ARCHITECT.v2", 14, 25);
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text("PERSONALIZED ACADEMIC BLUEPRINT | GENERATED BY GROQ LPU", 14, 32);
    
    y = 50;

    Object.entries(schedule).forEach(([day, tasks]) => {
      if (!tasks || tasks.length === 0) return;

      // --- DAY HEADER ---
      doc.setFillColor(241, 245, 249); // Light Gray
      doc.rect(14, y - 5, pageWidth - 28, 10, "F");
      doc.setTextColor(79, 70, 229); // Indigo
      doc.setFont("helvetica", "bold");
      doc.setFontSize(14);
      doc.text(day.toUpperCase(), 18, y);
      y += 12;

      tasks.forEach((task) => {
        // --- TASK CARD LOGIC ---
        const isWeak = weakSubjects.includes(task.subject);
        const isBreak = task.type === "break" || task.subject.toLowerCase().includes("break");

        // Subtle Border for Task
        doc.setDrawColor(226, 232, 240);
        doc.line(18, y - 4, pageWidth - 18, y - 4);

        // Time Section
        doc.setTextColor(100, 116, 139);
        doc.setFontSize(9);
        doc.setFont("helvetica", "bold");
        doc.text(`${task.start} - ${task.end}`, 20, y);

        // Subject Section
        if (isBreak) {
          doc.setTextColor(234, 179, 8); // Yellow for Break
        } else if (isWeak) {
          doc.setTextColor(217, 70, 239); // Fuchsia for Weak
        } else {
          doc.setTextColor(15, 23, 42); // Dark Slate
        }
        
        doc.setFontSize(11);
        doc.text(task.subject + (isWeak ? " [PRIORITY]" : ""), 55, y);

        // Activity Section
        doc.setTextColor(71, 85, 105);
        doc.setFont("helvetica", "normal");
        doc.setFontSize(10);
        
        // Wrap text for long activities
        const activityText = doc.splitTextToSize(task.activity, pageWidth - 100);
        doc.text(activityText, 95, y);

        // Dynamic spacing based on text length
        y += (activityText.length * 5) + 5;

        // Page break check
        if (y > 275) {
          doc.addPage();
          y = 20;
        }
      });

      y += 10; // Space between days
    });

    // --- FOOTER ---
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(148, 163, 184);
      doc.text(`Page ${i} of ${pageCount} | Master Blueprint System`, pageWidth / 2, 290, { align: "center" });
    }

    doc.save(`Architect_Blueprint_${new Date().toLocaleDateString()}.pdf`);
  };
  // -- TAG SYSTEMS --
  const handleKeyDown = (e, type) => {
    if (e.key === 'Enter' && (type === 'sub' ? subjectInput : weakInput).trim()) {
      e.preventDefault();
      const val = (type === 'sub' ? subjectInput : weakInput).trim();
      if (type === 'sub') {
        if (!subjects.includes(val)) setSubjects([...subjects, val]);
        setSubjectInput("");
      } else {
        if (!weakSubjects.includes(val)) setWeakSubjects([...weakSubjects, val]);
        setWeakInput("");
      }
    }
  };

  const removeTag = (val, type) => {
    if (type === 'sub') setSubjects(subjects.filter(s => s !== val));
    else setWeakSubjects(weakSubjects.filter(s => s !== val));
  };

  // -- TIME SLOTS --
  const addFreeSlot = (day) => {
    setFreeTimeSlots({
      ...freeTimeSlots,
      [day]: [...freeTimeSlots[day], { start: "09:00", end: "11:00" }]
    });
  };

  const removeFreeSlot = (day, index) => {
    const updated = [...freeTimeSlots[day]];
    updated.splice(index, 1);
    setFreeTimeSlots({ ...freeTimeSlots, [day]: updated });
  };

  const toggleOffDay = (day) => {
    setOffDays((p) => p.includes(day) ? p.filter((d) => d !== day) : [...p, day]);
  };

  const generate = async () => {
    if (subjects.length === 0) return alert("Bhai, subjects list empty hai!");
    setLoading(true);
    try {
      const payload = { structuredData: { subjects, weakSubjects, freeTimeSlots, offDays } };
      const res = await axios.post(`${serverUrl}/api/ai-scheduler/generate`, payload);
      setSchedule(res.data.schedule);
    } catch (err) {
      alert("Groq Blueprint failed. Check API/Server.");
    }
    setLoading(false);
  };

  return (
    <div className="min-h-screen bg-[#020617] text-slate-200 p-4 md:p-8 font-sans selection:bg-cyan-500/30">
      <div className="fixed top-0 left-0 w-full h-full overflow-hidden -z-10">
        <div className="absolute top-[-10%] left-[-10%] w-[50%] h-[50%] bg-indigo-600/10 blur-[120px] rounded-full"></div>
        <div className="absolute bottom-[-10%] right-[-10%] w-[50%] h-[50%] bg-fuchsia-600/10 blur-[120px] rounded-full"></div>
      </div>

      <div className="max-w-7xl mx-auto">
        <header className="text-center mb-12">
          <h1 className="text-6xl font-black bg-gradient-to-r from-cyan-400 via-indigo-400 to-fuchsia-400 bg-clip-text text-transparent mb-2 tracking-tighter">
            STUDY_ARCHITECT.v2
          </h1>
          <p className="text-slate-500 font-bold tracking-[0.4em] uppercase text-[10px]">LPU Powered • Groq Inference</p>
        </header>

        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
          
          {/* LEFT: INPUTS */}
          <div className="lg:col-span-5 space-y-6">
            <div className="bg-slate-900/40 backdrop-blur-3xl border border-slate-800 p-8 rounded-[2.5rem] shadow-2xl">
              <h2 className="text-xl font-black mb-8 flex items-center gap-3 italic tracking-tighter border-b border-slate-800 pb-4 text-cyan-400">
                <Sparkles size={22} /> SYSTEM_CONFIG
              </h2>
              
              <div className="space-y-6">
                <div>
                  <label className="text-[10px] font-black text-slate-500 uppercase tracking-widest ml-1 mb-2 block">Master Subjects</label>
                  <div className="flex flex-wrap gap-2 mb-3">
                    {subjects.map(sub => (
                      <span key={sub} className="flex items-center gap-1.5 bg-indigo-500/10 border border-indigo-500/30 px-3 py-1.5 rounded-xl text-xs font-bold text-indigo-300 animate-in zoom-in">
                        {sub} <X size={14} className="cursor-pointer hover:text-white" onClick={() => removeTag(sub, 'sub')}/>
                      </span>
                    ))}
                  </div>
                  <div className="relative">
                    <Hash className="absolute left-4 top-3.5 text-slate-600" size={16}/>
                    <input className="w-full bg-slate-950/50 border border-slate-800 rounded-2xl pl-10 pr-4 py-3.5 focus:ring-2 focus:ring-indigo-500 outline-none transition-all text-sm" placeholder="Add subject..." value={subjectInput} onChange={(e) => setSubjectInput(e.target.value)} onKeyDown={(e) => handleKeyDown(e, 'sub')} />
                  </div>
                </div>

                <div>
                  <label className="text-[10px] font-black text-fuchsia-500 uppercase tracking-widest ml-1 mb-2 block">Focus Areas (Weak)</label>
                  <div className="flex flex-wrap gap-2 mb-3">
                    {weakSubjects.map(sub => (
                      <span key={sub} className="flex items-center gap-1.5 bg-fuchsia-500/10 border border-fuchsia-500/30 px-3 py-1.5 rounded-xl text-xs font-bold text-fuchsia-300">
                        <AlertCircle size={12}/> {sub} <X size={14} className="cursor-pointer hover:text-white" onClick={() => removeTag(sub, 'weak')}/>
                      </span>
                    ))}
                  </div>
                  <div className="relative">
                    <Plus className="absolute left-4 top-3.5 text-slate-600" size={16}/>
                    <input className="w-full bg-slate-950/50 border border-slate-800 rounded-2xl pl-10 pr-4 py-3.5 focus:ring-2 focus:ring-fuchsia-500 outline-none transition-all text-sm" placeholder="Define weak..." value={weakInput} onChange={(e) => setWeakInput(e.target.value)} onKeyDown={(e) => handleKeyDown(e, 'weak')} />
                  </div>
                </div>

                <div>
                  <label className="text-[10px] font-black text-slate-500 uppercase tracking-widest ml-1 mb-2 block">Blackout Days</label>
                  <div className="grid grid-cols-4 gap-2">
                    {daysOfWeek.map(day => (
                      <button key={day} onClick={() => toggleOffDay(day)} className={`py-2 rounded-xl text-[9px] font-black transition-all border ${offDays.includes(day) ? "bg-red-500/20 border-red-500 text-red-400" : "bg-slate-950/50 border-slate-800 text-slate-600"}`}>
                        {day.substring(0, 3).toUpperCase()}
                      </button>
                    ))}
                  </div>
                </div>
              </div>
            </div>

            <div className="bg-slate-900/40 backdrop-blur-3xl border border-slate-800 p-6 rounded-[2.5rem] shadow-2xl max-h-[350px] overflow-y-auto">
              <h2 className="text-sm font-black mb-4 flex items-center gap-2 text-slate-400">
                <Clock size={16} /> OPERATIONAL_WINDOWS
              </h2>
              {daysOfWeek.map(day => !offDays.includes(day) && (
                <div key={day} className="mb-3 p-4 bg-slate-950/30 rounded-2xl border border-slate-800/50">
                  <div className="flex justify-between items-center mb-3 text-xs font-black text-slate-400 tracking-widest uppercase">{day} <button onClick={() => addFreeSlot(day)} className="p-1.5 bg-indigo-600/20 text-indigo-400 rounded-lg hover:bg-indigo-600 hover:text-white transition-all"><Plus size={12}/></button></div>
                  {freeTimeSlots[day].map((slot, i) => (
                    <div key={i} className="flex items-center gap-2 mb-2 animate-in slide-in-from-left-4">
                      <input type="time" value={slot.start} className="bg-slate-900/80 border border-slate-800 rounded-lg text-[10px] p-2 text-cyan-400" onChange={e => {
                        const updated = [...freeTimeSlots[day]]; updated[i].start = e.target.value;
                        setFreeTimeSlots({...freeTimeSlots, [day]: updated});
                      }} />
                      <input type="time" value={slot.end} className="bg-slate-900/80 border border-slate-800 rounded-lg text-[10px] p-2 text-cyan-400" onChange={e => {
                        const updated = [...freeTimeSlots[day]]; updated[i].end = e.target.value;
                        setFreeTimeSlots({...freeTimeSlots, [day]: updated});
                      }} />
                      <button onClick={() => removeFreeSlot(day, i)} className="text-slate-700 hover:text-red-500 ml-1"><X size={14}/></button>
                    </div>
                  ))}
                </div>
              ))}
            </div>

            <button onClick={generate} disabled={loading} className="w-full bg-gradient-to-br from-indigo-600 to-fuchsia-700 hover:from-indigo-500 hover:to-fuchsia-600 text-white py-5 rounded-[2rem] font-black tracking-[0.2em] text-xs shadow-2xl transition-all transform active:scale-95">
              {loading ? "GENERATING_MATRIX..." : "INITIALIZE_BLUEPRINT"}
            </button>
          </div>

          {/* RIGHT: OUTPUT MATRIX */}
          <div className="lg:col-span-7">
            {schedule ? (
              <div className="space-y-6 animate-in fade-in duration-700">
                <div className="flex justify-between items-center bg-slate-900/40 backdrop-blur-3xl p-6 rounded-[2rem] border border-slate-800">
                  <div className="flex flex-col">
                    <h2 className="text-xl font-black italic tracking-tighter text-cyan-400 flex items-center gap-2">OUTPUT_MATRIX <Edit3 size={16} className="text-slate-500 opacity-50"/></h2>
                    <span className="text-[8px] text-slate-500 font-bold uppercase tracking-widest">Live Editing Enabled</span>
                  </div>
                  <div className="flex gap-3">
                    <button onClick={downloadPDF} className="flex items-center gap-2 bg-slate-800 px-5 py-2.5 rounded-2xl text-[10px] font-black hover:bg-slate-700 transition-all border border-slate-700"><Download size={14}/> PDF</button>
                    <button onClick={() => setSchedule(null)} className="p-2.5 bg-red-500/10 text-red-500 rounded-2xl hover:bg-red-500/20 border border-red-500/20 transition-all"><Trash2 size={18}/></button>
                  </div>
                </div>

                <div className="grid gap-6">
                  {Object.entries(schedule).map(([day, tasks]) => tasks.length > 0 && (
                    <div key={day} className="bg-slate-900/20 border border-slate-800/60 p-8 rounded-[2.5rem] relative overflow-hidden group">
                      <div className="absolute top-0 right-0 p-4 opacity-5 font-black text-6xl select-none uppercase tracking-tighter">{day.substring(0,3)}</div>
                      <h3 className="text-xs font-black text-slate-400 mb-6 flex items-center gap-3 uppercase tracking-[0.3em]"><Calendar size={14} className="text-indigo-500"/> {day}</h3>
                      <div className="grid gap-4">
                        {tasks.map((task, i) => (
                          <div key={i} className={`p-5 rounded-[1.5rem] border transition-all relative group/task ${task.type === "break" ? "bg-yellow-500/5 border-yellow-500/20" : "bg-slate-950/80 border-slate-800 hover:border-cyan-500/30 shadow-lg"}`}>
                            <div className="flex justify-between items-center mb-2">
                              <span className="text-[10px] font-bold text-cyan-500/70 flex items-center gap-1 uppercase tracking-tighter">
                                <Clock size={12}/> {task.start} — {task.end}
                              </span>
                              <div className="flex items-center gap-2">
                                {weakSubjects.includes(task.subject) && <span className="text-[8px] bg-fuchsia-500/20 text-fuchsia-400 px-2 py-0.5 rounded-full font-black border border-fuchsia-500/20">WEAK_SPOT</span>}
                                <button onClick={() => removeTaskFromSchedule(day, i)} className="opacity-0 group-hover/task:opacity-100 text-slate-600 hover:text-red-500 transition-all"><XCircle size={14}/></button>
                              </div>
                            </div>
                            <input className="w-full bg-transparent font-black text-slate-100 outline-none mb-1 focus:text-cyan-400 text-sm tracking-tight border-b border-transparent focus:border-cyan-900/50" value={task.subject} onChange={(e) => handleEditSchedule(day, i, "subject", e.target.value)} />
                            <textarea className="w-full bg-transparent text-xs text-slate-500 outline-none resize-none h-auto focus:text-slate-300 border-none scrollbar-hide" rows="1" value={task.activity} onChange={(e) => handleEditSchedule(day, i, "activity", e.target.value)} />
                          </div>
                        ))}
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            ) : (
              <div className="h-full min-h-[600px] flex flex-col items-center justify-center bg-slate-900/10 border-2 border-dashed border-slate-800 rounded-[3rem] text-slate-800 group hover:border-slate-700 transition-all duration-1000">
                <BookOpen size={80} className="mb-6 opacity-5 group-hover:opacity-10 group-hover:rotate-12 transition-all duration-700" />
                <div className="text-center space-y-2">
                  <p className="font-black uppercase tracking-[0.5em] text-xs opacity-20">Awaiting_Neural_Sync</p>
                  <p className="text-[10px] font-bold opacity-10 uppercase tracking-widest">Configure parameters to begin synthesis</p>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

export default AIScheduler;